kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpserver
  labels:
    app: httpserver
    version: v1
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      containers:
        - name: httpserver
          image: 190219044/httpserver:argocd-demo
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: VERSION
              value: "v1.0.0"

