apiVersion: v1
kind: Service
metadata:
  name: httpserver
  labels:
    app: httpserver
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: httpserver
    version: v1
  type: NodePort

